[build]
  publish = "."

# Cache estendido para assets versionáveis
[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/assets/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
